name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: sudo apt-get install libavro-dev
    - name: build
      run: |
        mkdir build
        cd build
        cmake ..
        make -j
    - name: test
      run: |
        cd build
        ../tests/run.sh
