name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: sudo apt-get install libjansson-dev liblzma-dev libsnappy-dev zlib1g-dev
    - name: build Avro private branch
      run: |
        curl -sSL https://github.com/spektom/avro/archive/refs/heads/c_logical_types.tar.gz -o - | tar -zxf -
        mv avro-c_logical_types avro
        cd avro/lang/c
        mkdir build
        cd build
        cmake ..
        make -j
    - name: build avro2json
      run: |
        mkdir build
        cd build
        cmake -DZLIB_LIBRARY=/usr/lib/x86_64-linux-gnu/libz.a -DAVRO_LIBRARY=../avro/lang/c/build/src/libavro.a -DAVRO_INCLUDE_DIR=../avro/lang/c/src ..
        make -j
    - name: test
      run: |
        cd build
        ../tests/run.sh
