name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: sudo apt-get install libavro-dev libjansson-dev liblzma-dev libsnappy-dev zlib1g-dev
    - name: build
      run: |
        mkdir build
        cd build
        cmake -DZLIB_LIBRARY=/usr/lib/x86_64-linux-gnu/libz.a ..
        make -j
    - name: test
      run: |
        cd build
        ../tests/run.sh
